import os, json
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
EXP_DIR = os.path.join(ROOT, 'experiment_res', 'experiments')
OUT_MD = os.path.join(ROOT, 'experiment_res', 'gpu_diagnostics.md')

runs = []
for name in sorted(os.listdir(EXP_DIR)):
    run_dir = os.path.join(EXP_DIR, name)
    if not os.path.isdir(run_dir):
        continue
    # skip trial runs from tuning/benchmarks
    if 'trial' in name.lower():
        continue
    gj = os.path.join(run_dir, 'gpu_util_report.json')
    if not os.path.exists(gj):
        continue
    try:
        with open(gj, 'r') as f:
            data = json.load(f)
    except Exception as e:
        continue
    runs.append((name, data))

# compute stats
rows = []
valid_utils = []
valid_max = []
valid_mem = []
for name, d in runs:
    avg = d.get('avg_gpu_util', 0.0)
    mx = d.get('max_gpu_util', 0)
    mem = d.get('avg_gpu_mem_mb', 0.0)
    rows.append({'name': name, 'avg_gpu_util': avg, 'max_gpu_util': mx, 'avg_gpu_mem_mb': mem, 'elapsed_s': d.get('elapsed_s'), 'samples': d.get('samples')})
    # consider values > 0 as valid
    if avg and avg > 0:
        valid_utils.append(avg)
    if mx and mx > 0:
        valid_max.append(mx)
    if mem and mem > 0:
        valid_mem.append(mem)

overall = {
    'runs_total': len(rows),
    'valid_avg_count': len(valid_utils),
    'valid_max_count': len(valid_max),
    'valid_mem_count': len(valid_mem),
}
if valid_utils:
    overall['avg_of_avg_gpu_util'] = sum(valid_utils)/len(valid_utils)
else:
    overall['avg_of_avg_gpu_util'] = 0.0
if valid_max:
    overall['avg_of_max_gpu_util'] = sum(valid_max)/len(valid_max)
else:
    overall['avg_of_max_gpu_util'] = 0.0
if valid_mem:
    overall['avg_of_avg_gpu_mem_mb'] = sum(valid_mem)/len(valid_mem)
else:
    overall['avg_of_avg_gpu_mem_mb'] = 0.0

# write markdown
with open(OUT_MD, 'w') as f:
    f.write('# GPU Diagnostics Report\n\n')
    f.write('This report aggregates `gpu_util_report.json` from each run under `copilot_plan/experiment_res/experiments/`.\n\n')
    f.write('## Summary\n\n')
    f.write(f'- Runs found with GPU report: {overall["runs_total"]}\n')
    f.write(f'- Runs with non-zero avg util: {overall["valid_avg_count"]}\n')
    f.write(f'- Runs with non-zero max util: {overall["valid_max_count"]}\n')
    f.write(f'- Runs with non-zero avg mem: {overall["valid_mem_count"]}\n')
    f.write(f'- Avg of avg GPU util (across runs with non-zero): {overall["avg_of_avg_gpu_util"]:.2f}\n')
    f.write(f'- Avg of max GPU util (across runs with non-zero): {overall["avg_of_max_gpu_util"]:.2f}\n')
    f.write(f'- Avg of avg GPU mem MB (across runs with non-zero): {overall["avg_of_avg_gpu_mem_mb"]:.1f} MB\n\n')

    f.write('## Per-run details\n\n')
    f.write('| Run | avg_gpu_util | max_gpu_util | avg_gpu_mem_mb | elapsed_s | samples |\n')
    f.write('|---|---:|---:|---:|---:|---:|\n')
    for r in rows:
        f.write(f"| {r['name']} | {r['avg_gpu_util']:.2f} | {r['max_gpu_util']} | {r['avg_gpu_mem_mb']:.1f} | {r.get('elapsed_s','-')} | {r.get('samples','-')} |\n")

    f.write('\n## Notes and Recommendations\n\n')
    if overall['valid_avg_count'] == 0:
        f.write('- No runs recorded non-zero GPU util: GPU monitoring may have failed or not been enabled. Verify `monitor_and_train.py` writes valid samples.\n')
    else:
        if overall['avg_of_avg_gpu_util'] < 50:
            f.write('- Observed low average GPU utilization across runs (<50%). Consider increasing `batch` size, enabling mixed precision, or reducing IO bottlenecks (increase `num_workers`, optimize dataset pipeline).\n')
        else:
            f.write('- GPU utilization appears healthy on average.\n')
    if overall['valid_mem_count'] > 0 and overall['avg_of_avg_gpu_mem_mb'] < 1000:
        f.write('- Average GPU memory usage is low; potential to increase batch size for higher throughput.\n')
    f.write('\nGenerated by copilot script.\n')

print('Wrote', OUT_MD)
print('Done.')
